### ISSUE TITLE
halde-test breaks test-ref.o

### ISSUE THREAD

**Issue by heckenscherenmann** [stormofice/sp-custom-tests#4]
Upon running run.sh, `test-ref.o` has different behaviour than before, also when it is being run with the public, unmodified file `test.c`. Often just leads to segfault.
Getting a new copy of `test-ref.o` fixes the issue until `run.sh` is run again

**Comment by stormofice** [comment]
An old version of the run script, had some issues concerning `test.c`. However these should be fixed as of d8e553d4044337edb74e7f85ef15cdba224b3305. In newer versions of the run script, everything should be contained to a file called `custom_test.c` as `test.c` will not be used by the script.

If you downloaded the `run.sh` script once, then you should re-download it to get the new changes or run it like this `bash <(curl -s https://raw.githubusercontent.com/stormofice/sp-custom-tests/main/aufgabe3/run.sh)` (which always fetches new versions).

It is not recommended to download `run.sh` once, as issues (like this one) may arise after the first release, which would persist in an old copy.

**Comment by heckenscherenmann** [comment]
I have always used the newest version with `bash <(curl -s https://raw.githubusercontent.com/stormofice/sp-custom-tests/main/aufgabe3/run.sh)` and did so once again, but the issue persists. 
Also I mistyped in my original issue, I meant that the test breaks `halde-ref.o` instead of `test-ref.o`.

**Comment by stormofice** [comment]
The test (**and your makefile**) should leave `halde-ref.o` untouched, as it is only used for compilation purposes.

Would you mind sharing the output of `run.sh` until it crashes and your execution environment (mainly the OS/Terminal you are using)?

If the script gets this far, could you also share `reference_out` and `local_out`?
These files *should* contain the output of the last test case which got executed (normally).

I am a bit clueless, as to what is going wrong at the moment, could you also verify the checksum of `halde-ref.o` [using ` md5sum halde-ref.o`]?
It shoud be:
`4d6d90709bece96835e69907a632412d  halde-ref.o`

**Comment by heckenscherenmann** [comment]
[out.zip](https://github.com/stormofice/sp-custom-tests/files/6602878/out.zip)

The test itself does not crash (though malloc_simple should not fail), it's that after running the test the command `./test-ref` shows different behaviour (mostly segfault) than before. My own tests, which are very similar to malloc_simple, also fail from this point on.
Replacing `halde-ref.o` with the original copy fixes the issue, that is why I assumed that this file is being tempered with somehow.
The checksum is the same as yours though...
`4d6d90709bece96835e69907a632412d  halde-ref.o`

I am using `GNU bash, version 5.0.17` on PopOs

**Comment by stormofice** [comment]
`test-ref` gets created anew for every test case which runs. 
This is done to compare the output of your own solution to the reference one. I believe this explains why `test-ref` behaves differently after running the tests, as it will contain the last ran test. 

If you want to get your own `test-ref` back, you need to build it again (with your `test.c` and `halde-ref.o`).

> Replacing halde-ref.o with the original copy fixes the issue, that is why I assumed that this file is being tempered with somehow.
> The checksum is the same as yours though...

I think this is the case due to the fact, that `make` only rebuilds targets where the modification dates of its dependencies (e.g. `test.c`, `halde-ref.o`) have changed. If you now replace `halde-ref.o`, it thinks that something changes and successfully re-compiles it to the original `test-ref`.
In my opinion, your `Makefile` should not list `halde-ref.o` as a dependency in your targets, as you will not change the file and it does not need to be build by `make`. 
Removing `halde-ref.o` [temporarily] from your targets should fix the issue of your own tests not working after running the custom test.

As to why `test-ref` segfaults:
I am uncertain on the exact reasons, however it could happen that if a test fails and you exit afterwards, that `test-ref` will be left in an unusable state. If this happens re-running the custom test or rebuilding `test-ref` using your own `test.c` should fix the issue.
